# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Always 20 years away
email: karl.sundequist.blomdahl@gmail.com
description: >
  My thoughts about things that will always be 20 years away (from some point
  in the space and time continuum). Also some other things that I find worthwhile
  discussing.
baseurl: ""
url: "http://chicoryn.github.io"
twitter_username: chicoryn
github_username:  chicoryn

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight